# Generated by Django 3.0.7 on 2022-05-13 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20201221_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.CharField(max_length=20)),
                ('tarih', models.DateTimeField(auto_now_add=True, null=True)),
                ('fiyat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Satimlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.CharField(max_length=20)),
                ('tarih', models.DateTimeField(auto_now_add=True, null=True)),
                ('fiyat', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultimage.jpg', null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
